### ISSUE TITLE
Add a zoom to full map extent map control

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#109]
Zoom to full extent of province. Could put icon between prev/next extent controls?

**Comment by cmhodgson** [comment]
I found a tool that did this nicely, it adjoins the existing zoom in/out controls. Have a look.

**Comment by mraross** [comment]
Looks great. Can you change the bbox to about the same extent as the physical address viewer in google earth?

**Comment by cmhodgson** [comment]
The existing control that I made use of was intended to zoom out to the minimum, and had an option to center on a specified bounds. Depending on the size and resolution of your screen, the min zoom might show you more or less than exactly all of the province. I changed it so that it just zooms to whatever level allows all of BC to be visible, and I also reduced the map's min zoom constraint so that it was possible to fit all of BC into an even smaller screen. 

Note that we are stuck with the fixed zoom levels (unlike google earth) so again depending on the size of your screen, the zoom level that fits all of BC may have to show you significantly more than just BC (because the next zoomed-in level would be too tight and not fit all of BC).
