### ISSUE TITLE
IN ALE, Show in Map function should link to Location Services in Action instead of gmaps

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#116]

**Comment by cmhodgson** [comment]
Done locally. Note that rather than use the lat/lon, it uses the input addressString value, ie. it links to:
https://ols-demo.apps.gov.bc.ca/index.html?q=1207+douglas+st
instead of:
https://ols-demo.apps.gov.bc.ca/index.html?q=48.4256448,-123.3647132

This has the benefit of displaying the actual info about the address match in the demo app. I've set it up so that the ALE now uses the same "?env=(dlv|tst|rri)" options that the ols-demo uses, in order to specify which geocoder to use. It also passes the env option through to the demo app, so that it uses the same version of the geocoder, which ensures consistency of the results being shown.

**Comment by mraross** [comment]
The demo app should call the ALE with the fullAddress value, not the addressString value.

**Comment by cmhodgson** [comment]
Change made and committed to github, viewable here: https://cmhodgson.github.io/ols-devkit/ale/
