### ISSUE TITLE
When you add a reverse geocoded address to route, parcelPoint is used instead of accessPoint

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#135]
In Location Services in Action demo app, zoom in to a small area and turn on accessPoints layer. Click on an accessPoint then click plus icon ("+") to add accessPoint to current route. App will display a parcelPoint for the address instead. Same behavior observed for parcelPoints layer.

**Comment by cmhodgson** [comment]
In all cases where the "+" is available, the address of the location is sent to the geocoder, and the number 1 match is returned, and used. The geocoding function always uses the access point because it is more applicable to routing than the site point. There is no mechanism to pass the specific location, or any geocoder parameters, to the geocoding function - because the pop-up window that has the "+" in it is unaware of any of these details. Even if we were to add such a mechanism, I think the effect of this change, which is that two stops in the route with the exact same address could refer to two different points, is more confusing than the current situation where adding a site point actually adds the access point location. I guess you could argue that only the access points, and not the site points, should have the "+" button, but if you only have the site points displayed then it is still useful.

**Comment by cmhodgson** [comment]
Ignore my previous comment, as my understanding of both the expectation and what was really happening were backwards. I believe I have now achieved the desired result:
http://office.refractions.net/~chodgson/gc/ols-demo/index.html?env=dlv

**Comment by cmhodgson** [comment]
Committed to github and in pull request.

**Comment by mraross** [comment]
Verified in prod
