### ISSUE TITLE
In route tab, add a search button just like in address tab

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#69]
Add a search button to From and To fields

**Comment by cmhodgson** [comment]
This search behaves slightly differently - after you click it (or press enter), the addressString of the best match is placed into the input field. This is so that you can tell what your input actually matched to. Perhaps we want this same behaviour on the the geocoder, but if you want to be able to incrementally adjust your input, you can't do that anymore. For example, if you type "garbage" into the field, you actually get back a province match for BC, and I think that for the router it is necessary to make that clear by changing the input field. However for the geocoder, I'm not so sure.

**Comment by cmhodgson** [comment]
Remove the search button. Require user to select from autocomplete. Remove extra info from router from/to points, only display addressString.

**Comment by cmhodgson** [comment]
Search button removed; to enter a lat,lng you must push enter after typing/pasting the numbers.
Route from/to points only show the addressString in the pop-up when clicked.

**Comment by cmhodgson** [comment]
In delivery now.
