### ISSUE TITLE
Manually reordering route stops in Firefox doesn't work

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#89]
When you try to drag a stop to a new position in the list, it just doesn't move.

**Comment by cmhodgson** [comment]
Apparently this is cause by not one but two, known, old bugs in firefox - https://github.com/RubaXa/Sortable/issues/370 - relating to using a button as the drag handle. I'm using a button because it makes it look nice with the bootstrap form CSS that I'm using. But there is a workaraound, not sure what it does but it seems to work so I've implemented it.

**Comment by cmhodgson** [comment]
Fix is in delivery now.

**Comment by mraross** [comment]
Verified
