### ISSUE TITLE
Parcel points disappear below a certain scale

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#97]
Tested in:
 https://cmhodgson.github.io/ols-devkit/ols-demo/index.html?test=true

This might already be fixed in your dev environment.

**Comment by cmhodgson** [comment]
I cannot duplicate this in any environment. You mean to say that if you zoom in to the max, the "Addresses - parcel point" little blue squares disappear? I don't think I've ever seen that happen...

**Comment by cmhodgson** [comment]
This is caused by problems with the interactions between the dynamic json layer and the clustering functions. I have try various alternative approached to get the clustering to work but it essentially needs to be integrated into the dynamic layer in order to work properly. This may be possible but for now, in order to return the test environment to a working state, I have removed the clustering function.

**Comment by mraross** [comment]
verified in test
